using UnityEngine;

public class RoadShaderApply : MonoBehaviour
{
    public Material roadHighlightMaterial; // Assign in Inspector (your custom shader material)

    void Start()
    {
        // The map texture generated by Online Maps
        Texture2D mapTexture = OnlineMaps.instance.texture;

        // Set the map texture as _MainTex on your highlight material
        roadHighlightMaterial.SetTexture("_MainTex", mapTexture);

        // If you have a Renderer on this GameObject (e.g., a quad),
        // apply the highlight material to that renderer:
        GetComponent<Renderer>().material = roadHighlightMaterial;

        OnlineMaps.instance.OnMapUpdated += OnMapRedrawn;
    }

    void OnMapRedrawn()
    {
        // The map was just updated, so apply your custom logic/material now.
        roadHighlightMaterial.SetTexture("_MainTex", OnlineMaps.instance.texture);
    }

}
